name: Vim Docs

on:
  push:
    branches-ignore:
      - main
    paths:
      - README.md
      - .github/workflows/vim-docs.yml

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Update Vim docs
    steps:
      - uses: actions/checkout@v6
      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: ${{ github.event.repository.name }}
          version: "Neovim >= 0.10.0"

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Update docs"
